### ISSUE TITLE
X Gantry Assembly documentation

### ISSUE THREAD

**Issue by JesseLeonard** [opulo-inc/lumenpnp#466]
Order of assembly has you put the back on first but you need access to the backside of the front part to do the belt installation. Suggest moving the installation of the backing plate and rollers to the end after finishing with the stepper motor.

**Comment by JesseLeonard** [comment]
Looking at Build 2.0.1 Docs:
Steps 7, 12, 13 have you work through attaching FDM-11 and FDM-12 together with v-rollers in between.
These three steps and pictures should be moved to after step 25, i.e. after you've completed belt tensioning and any belt trimming. FDM-12 can't be installed during belt tensioning since it will be in the way of getting to the belt-side of FDM-40 and FDM-41.

The photos for steps 24, 24, 25, 25 already do not have FDM-12 installed since it has to be off in order to do z-axis belt tensioning.

**Comment by Memnarch1113** [comment]
I am realizing that I did not actually address this issue. I believe it is still wrong in the docs, and we need to make it so that assembling the Z-axis stuff happens before [attaching the front and back X Gantry](https://docs.opulo.io/docs/mechanical-assembly/x-gantry-assembly/#attaching-x-gantry-front-and-back)

**Comment by sphawes** [comment]
This has been fixed, all Z gantry assembly happens before front and back X Gantry assembly.
