### ISSUE TITLE
[Suggestion] 12mm Strip Feeder STL is positioned inversely should be rotated upside down. 

### ISSUE THREAD

**Issue by kaklik** [opulo-inc/lumenpnp#613]
The 12mm strip feeder is positioned upside down in STL printing file. 

![image](https://user-images.githubusercontent.com/1194177/194599860-f5cb8d4c-eae1-48fe-b0a5-5124981c23aa.png)

That results in malformed print:

![IMG_20221007_181613](https://user-images.githubusercontent.com/1194177/194600478-4469060c-f620-44a7-acc6-021e5bdbd0e3.jpg)

That could be easily fixed by inverting the STL file. Like that: 

![image](https://user-images.githubusercontent.com/1194177/194600630-6301375e-f003-49aa-a61f-0552f8e88189.png)

I think that could be trouble for many users, which do not notice that before starting the print.

**Comment by sphawes** [comment]
Thank you for the note @kaklik! we're actually moving to removing these cuts because they can cause real trouble when pulling tape through, so ill close this. I'm also unsure as to how we can get this flipped, short of remodeling or rotating the entire geometry in freecad which would be quite a heavyhanded solve. We'll keep an eye on misleading part orientations in the future!
