### ISSUE TITLE
Clarify which NEMA11 is used 

### ISSUE THREAD

**Issue by saloid** [opulo-inc/lumenpnp#622]
v3.0.1 BOM contains link to NEMA11 drive used on head. But it's not clear which option is used (there are several options available).
So I think it's better to mention in BOM which exactly is need to be bought:
![image](https://user-images.githubusercontent.com/22222390/198683606-b976044f-32bc-4c85-b261-d32ee4d2d9b5.png)

**Comment by G-Pereira** [comment]
Thanks @saloid in the mean time let me state that the suitable motor part number between those you have listed is 11HY3406-9SK842 since it is compatible with the CP40 nozzle holder and uses a M5 screw on the rear to connect a M5 rotational fitting. Having that said, one of us will clarify the exact part number we are targeting/recommend probably based on what is being shipped in Opulo kits.
