### ISSUE TITLE
V3 Resets "Randomly"

### ISSUE THREAD

**Issue by cjstangman** [opulo-inc/lumenpnp#651]
Hey All,

I have encountered my PNP resetting during the calibration process, which is really annoying when you are in the middle of something and have to rehome and start over. It is so prevalent during tool changes that I am unable to calibrate the automatic tool changer. It seems to happen as the staging plate moves when the nozzle enters or exits a tip.

Has anyone else experienced this, or do I have a bad motherboard?

Thanks.

**Comment by fabiankropp** [comment]
I did experience the same thing with an V2 - version of the Lumen. Slowing it down has helped a bit so far. (max speed in code set to 6000)
Or it my have been fixed by selecting a different USB port (as I had to change both)

Anyhow, it happened to me a lot before the changes, now with latest OpenPNP and the described changes it at least got less prominent.
