### ISSUE TITLE
Rotation Stepper Runaway Heat

### ISSUE THREAD

**Issue by neatstranger** [opulo-inc/lumenpnp#719]
Please close this if it's not inline with dev workflow. Mostly just wanted to inform you of a problem. 

Last night, I left my machine (V3.1) plugged into power when I left the office. While working on the machine, I accidentally touched the steppers that control the rotational axis. 

My guess would be that it was around 100C. Which had deformed the motor mount pretty severely.

Anyway, think this should be a simple setting in marlin to step down the holding power of those motors when not in use.

**Comment by sphawes** [comment]
hey there, thanks for the report! can you try flashing firmware from this release and see if the issue persists?: https://github.com/opulo-inc/lumenpnp/releases/tag/v3.2.0

I'd also love to see your OpenPnP `machine.xml` file as well, that should help!

**Comment by nathanaelhuffman** [comment]
I am noticing similar behavior on my unit. both were too hot to keep my hand on them and had started deforming the z gantries.

I am using the firmware from that release (https://github.com/opulo-inc/lumenpnp/releases/download/v3.2.0/v3.0-lumenpnp-firmware-01.bin).

I'm going to let them cool and try the v3.1 firmware (I have the linear rail mod) but seemingly that shouldn't make a difference to the rotation motors?

I've attached my machine.xml (renamed to txt due to github) which started from the file in the 3.2 release also:
[machine.txt](https://github.com/opulo-inc/lumenpnp/files/14794946/machine.txt)

**Comment by nathanaelhuffman** [comment]
Here's a debug.opulo.io output when the issue is not presenting (looks normal, full output):
[2024-03-28T20_37_38.330Z-tmctest.txt](https://github.com/opulo-inc/lumenpnp/files/14795558/2024-03-28T20_37_38.330Z-tmctest.txt)

And the Test TMC Drivers output when it is presenting:
[2024-03-28T20_56_16.170Z-tmctest.txt](https://github.com/opulo-inc/lumenpnp/files/14795595/2024-03-28T20_56_16.170Z-tmctest.txt)

I ran this multiple times  with similar outputs until I power cycled the machine and then the output would return to normal.

**Comment by nathanaelhuffman** [comment]
On discord, it was pointed out that I was incorrectly power sequencing the lumen by plugging USB in first and then plugging in the 24V. I have not reproduced this again since flipping the order and doing 24V first, so I'm just going to leave this here in case it helps someone else with a similar issue.

Presumably doing the sequence in the wrong order allows marlin to begin booting, but the stepper controllers don't get properly set up, since they weren't necessarily available a the correct point in the bootup process.

**Comment by atanisoft** [comment]
@sphawes perhaps on rev5+ an PMIC (or similar) could be added to hold the MCU in a reset state until both 5v and 24v is UP? This might mitigate the sequencing some

**Comment by nathanaelhuffman** [comment]
> Glad that's helped! I've run a test on a machine powering USB, then powering the 24v rail, and I haven't been able to replicate the issue. @nathanaelhuffman what version motherboard are you running? is this self-built? sounds to me like this issue is a corner case with power sequence _plus_ some other variable.

This was an early diy kit (Order #1169), which I have modified to match the 3.2 release with rails and new prints, and purchased the updated mobo and 2nd head stuff from you (Order #1531) plus some staging plates and feeders on other orders. So while I "built" it, the only self-sourced stuff has been the rails and PLA, the rest of the stuff came direct from Opulo.  This does mean I have the original kit power supply still, but I don't think I have enough feeders loaded right now that it's a problem.
